### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by ayush-9s** [rvicentecruz/Xcompact3d_Pipe_CHT#1]
Hello,

I am trying to build the project, but am unable to do so. I have the gnu fortran compiler (version 11.3.0) and the default settings in the makefile did not work so I tried with other settings (which were commented out in the makefile itself). In every case, the build process stopped. I also tried using the settings I had for the original Xcompact3d (which is working without any issues), but still could not get the project to be built. I have attached the makefile and the errors I am facing here. I wanted to know if there is some requirement I need to download or is the fault due to the compiler settings I have. 
[log.txt](https://github.com/rvicentecruz/Xcompact3d_Pipe_CHT/files/12035606/log.txt)
[Makefile.txt](https://github.com/rvicentecruz/Xcompact3d_Pipe_CHT/files/12035611/Makefile.txt)

Any help would be much appreciated.
Thanks,
Ayush.

**Comment by rvicentecruz** [comment]
Hello,

Thank you for reporting this issue. Indeed, depending on the compilation options, the compiler may reject the computation of the variable `c1` as it was previously done in the subroutine `set_viscfilter_coefficients`. In 630d7c2079ce65dc5d197c1543a783fde6731274, I've implemented its direct value `c1=0.44`, as it is done in the file input.i3d (variable `cnu`). Could you please try to recompile ?

**Comment by ayush-9s** [comment]
I am able to compile it now without any issues 
Thanks for the speedy reply

Regards,
Ayush.
